### ISSUE TITLE
Crash on android when changed orientation

### ISSUE THREAD

**Issue by ggawryal** [Xenox40/Geometric-Wars#22]
com.badlogic.gdx.utils.GdxRuntimeException: #iterator() cannot be used nested.
        at com.badlogic.gdx.utils.Array$ArrayIterator.hasNext(Array.java:584)
        at com.badlogic.gdx.graphics.g3d.Material.<init>(Material.java:68)
        at com.badlogic.gdx.graphics.g3d.Material.<init>(Material.java:62)
        at com.badlogic.gdx.graphics.g3d.Material.copy(Material.java:74)
        at com.badlogic.gdx.graphics.g3d.ModelInstance.invalidate(ModelInstance.java:269)
        at com.badlogic.gdx.graphics.g3d.ModelInstance.invalidate(ModelInstance.java:283)
        at com.badlogic.gdx.graphics.g3d.ModelInstance.copyNodes(ModelInstance.java:226)
        at com.badlogic.gdx.graphics.g3d.ModelInstance.<init>(ModelInstance.java:154)
        at com.badlogic.gdx.graphics.g3d.ModelInstance.<init>(ModelInstance.java:146)
        at com.badlogic.gdx.graphics.g3d.ModelInstance.<init>(ModelInstance.java:62)
        at com.badlogic.gdx.graphics.g3d.ModelInstance.<init>(ModelInstance.java:182)
        at com.geometric.wars.enviromentparts.Wall.<init>(Wall.java:25)
        at com.geometric.wars.maps.MapLoader.addWall(MapLoader.java:99)
        at com.geometric.wars.maps.MapLoader.addObjectsToMap(MapLoader.java:73)
        at com.geometric.wars.maps.MapLoader.load(MapLoader.java:50)
        at com.geometric.wars.scene.SceneManager.loadGame(SceneManager.java:32)
        at com.geometric.wars.screens.GameScreen.<init>(GameScreen.java:20)
        at com.geometric.wars.GeometricWars.create(GeometricWars.java:39)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:311)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1511)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)

**Comment by Xenox40** [comment]
Partial fixed in https://github.com/Xenox40/Geometric-Wars/commit/8b08154eecbf29d6a4bc52ad9d629c09e62047a0.

Now hitting play button with landscape orientation calls exception.
